spring:
  rabbitmq:
    host: gerbil.rmq.cloudamqp.com
    port: 5672
    username: zgmugpkb
    password: zw9GCmLULPohHbkOsUcfnAOAbn5x_jXX
    virtual-host: zgmugpkb
  application:
    name: BatchSplitter
server:
  port: 9092
file:
  storage:
    path: ./data
